seed_everything: 42
trainer:
  enable_checkpointing: true
  accelerator: gpu
  devices: 1
  max_epochs: 1000
  gradient_clip_val: 1.0
  strategy: null
  sync_batchnorm: false
  precision: 32
  enable_model_summary: true
  weights_save_path: null
  num_sanity_val_steps: 2
  benchmark: true
