model:
  metrics:
    class_path: torchmetrics.MetricCollection
    init_args:
      metrics:
        psnr: torchmetrics.image.psnr.PeakSignalNoiseRatio
  autoencoder:
    class_path: ot_vae_lightning.networks.AutoEncoder
    init_args:
      in_features: 1
      in_resolution: 32
      latent_features: 128
      latent_resolution: 1
      double_encoded_features: true
      capacity: 8
      n_layers: 2
      down_up_sample: 2
      normalization: batchnorm
      activation: relu
      equalized_lr: false
      dropout: 0.0
      residual: false
  prior:
    class_path: ot_vae_lightning.prior.GaussianPrior
    init_args:
      loss_coeff: 0.1
      empirical_kl: false
data:
  train_val_split: 0.9
  seed: null
  train_batch_size: 512
  val_batch_size: 1024
  test_batch_size: 1024
  num_workers: 10

