seed_everything: null
trainer:
  logger: true
  checkpoint_callback: null
  enable_checkpointing: true
  callbacks:
    - class_path: pytorch_lightning.callbacks.RichProgressBar
  default_root_dir: null
  gradient_clip_val: null
  gradient_clip_algorithm: null
  process_position: 0
  num_nodes: 1
  num_processes: null
  devices: null
  gpus: null
  auto_select_gpus: false
  tpu_cores: null
  ipus: null
  log_gpu_memory: null
  progress_bar_refresh_rate: null
  enable_progress_bar: true
  overfit_batches: 0.0
  track_grad_norm: -1
  check_val_every_n_epoch: 1
  fast_dev_run: false
  accumulate_grad_batches: null
  max_epochs: 50
  min_epochs: null
  max_steps: -1
  min_steps: null
  max_time: null
  limit_train_batches: null
  limit_val_batches: null
  limit_test_batches: null
  limit_predict_batches: null
  val_check_interval: null
  flush_logs_every_n_steps: null
  log_every_n_steps: 50
  accelerator: null
  strategy: null
  sync_batchnorm: false
  precision: 32
  enable_model_summary: true
  weights_summary: top
  weights_save_path: null
  num_sanity_val_steps: 2
  resume_from_checkpoint: null
  profiler: null
  benchmark: null
  deterministic: null
  reload_dataloaders_every_n_epochs: 0
  auto_lr_find: false
  replace_sampler_ddp: true
  detect_anomaly: false
  auto_scale_batch_size: false
  prepare_data_per_node: null
  plugins: null
  amp_backend: native
  amp_level: null
  move_metrics_to_cpu: false
  multiple_trainloader_mode: max_size_cycle
  stochastic_weight_avg: false
  terminate_on_nan: null
model:
  metrics:
    class_path: torchmetrics.MetricCollection
    init_args:
      metrics:
        psnr: torchmetrics.image.psnr.PeakSignalNoiseRatio
  encoder:
    class_path: ot_vae_lightning.networks.CNN
    init_args:
      in_features: 1
      out_features: 128  # must double number of channels to allow for re-param trick
      in_resolution: 32
      out_resolution: 2
      intermediate_features: null
      capacity: 4
      n_layers: 2
      down_sample: 2
      up_sample: false
      normalization: batchnorm
      activation: relu
      equalizer_lr: false
      dropout: 0.0
      kernel_size: 3
      stride: 1
      padding: 1
      dilation: 1
      groups: 1
      bias: true
      residual: false
  decoder:
    class_path: ot_vae_lightning.networks.CNN
    init_args:
      in_features: 64
      out_features: 1
      in_resolution: 2
      out_resolution: 32
      intermediate_features: null
      capacity: 4
      n_layers: 2
      down_sample: false
      up_sample: 2
      normalization: batchnorm
      activation: relu
      equalizer_lr: false
      dropout: 0.0
      kernel_size: 3
      stride: 1
      padding: 1
      dilation: 1
      groups: 1
      bias: true
      residual: false
  prior:
    class_path: ot_vae_lightning.prior.GaussianPrior
    init_args:
      loss_coeff: 1e-3
      empirical_kl: false
data:
  root: /home/ubuntu/.cache
  no_pad: false
  train_val_split: 0.8
  seed: null
  train_batch_size: 250
  val_batch_size: 1000
  test_batch_size: 1000
  num_workers: 10
ckpt_path: null
