model:
  metrics:
    class_path: torchmetrics.MetricCollection
    init_args:
      metrics:
        psnr: torchmetrics.image.psnr.PeakSignalNoiseRatio
  plateau_metric_monitor: psnr
  expansion: 1
  encoder:
    class_path: ot_vae_lightning.networks.ViT
    init_args:
      image_size: 28
      patch_size: 7
      dim: 64
      depth: 6
      heads: 4
      mlp_dim: 256
      channels: 1
      dim_head: 32
      dropout: 0.1
      emb_dropout: 0.
      n_embed_tokens: 2
      n_input_tokens: null
      output_tokens: embed
      patch_to_embed: true
      embed_to_patch: false
  decoder:
    class_path: ot_vae_lightning.networks.ViT
    init_args:
      image_size: 28
      patch_size: 7
      dim: 64
      depth: 6
      heads: 4
      mlp_dim: 256
      dim_head: 32
      channels: 1
      dropout: 0.1
      emb_dropout: 0.
      n_embed_tokens: null
      n_input_tokens: 1
      output_tokens: embed
      patch_to_embed: false
      embed_to_patch: true
  prior:
    class_path: ot_vae_lightning.prior.GaussianPrior
    init_args:
      reparam_dim: 1
      loss_coeff: 0.1
      empirical_kl: false
      annealing_steps: 0
      fixed_var: false
data:
  train_val_split: 0.9
  seed: null
  train_batch_size: 200
  val_batch_size: 200
  test_batch_size: 200
  num_workers: 8
