trainer:
  logger:
    class_path: pytorch_lightning.loggers.WandbLogger
    init_args:
      project: ot-vae-lightning
      entity: gip
      dir: vae
      log_model: true
      name: auto-diffuser-vit
model:
  autoencoder: null
  encoder:
    class_path: ot_vae_lightning.networks.ViT
    init_args:
      image_size: 64
      patch_size: 8
      dim: 256
      depth: 3
      preprocess_depth: null
      heads: 8
      channels: 3
      dropout: 0.1
      emb_dropout: 0.
      n_embed_tokens: 1
      n_input_tokens: null
      output_tokens: embed
      patch_to_embed: true
      embed_to_patch: false
      num_classes: null
      time_dependant: false
  decoder:
    class_path: ot_vae_lightning.networks.ViT
    init_args:
      image_size: 64
      patch_size: 8
      dim: 256
      depth: 2
      heads: 8
      channels: 3
      dropout: 0.1
      emb_dropout: 0
      n_embed_tokens: null
      n_input_tokens: 1
      output_tokens: embed
      patch_to_embed: false
      embed_to_patch: true
      num_classes: null
      time_dependant: false
